const HerbsAPI=[
    {
        id: '1',
        category: 'Herbs',
        name:'Basil',
        color: 'green – brown ',
        originOfBasil: 'Egypt',
        Type: ' conventional basil  and  organic basil .',
        harvestSeason: 'June to October  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'purity 99%',
        Moisture: 'Moisture 8 - 10%max.',
        Usage: 'herbs , Medicinal plants , aromatic , herbal tea, Seasonings, flavor, spices, dried vegetables . ',
        feet: '20 ft container load of basil :6 ton - 40 ft container load of basil :11 ton .',
        description:' Same smell of the fresh basil. Free of alive or dead insects Free of mouldy or bad smell, Moisture  8 - 10%max Vaporous oil min. 0.3%',
        image: 'https://i.ibb.co/HVYGFy7/bsil2.png',
        photo: 'https://i.ibb.co/H2TT0YS/Basil.png'
    },
    {
        id: '2',
        category: 'Herbs',
        name:'Calendula – Marigold',
        color: ' Orange  ',
        originOfBasil: 'Egypt',
        Type: 'Foreign Materials or Ash 0% ',
        harvestSeason:  'conventional calendula, marigold and organic calendula, marigold. ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'purity 99%',
        Moisture: 'Moisture max 5-10%.',
        Usage: 'Part use: flowers, petal, tea bag cut',
        feet: '20 ft container load of calendula, marigold :4 ton - 40 ft container load of calendula, marigold :  8 ton.  ',
        description:' Calendula, marigold is applied to the skin and mucous membrane for inflammations and skin diseases  Calendula, marigold has been used as a tea for various conditions and as a topical cream .Stem & bells max 3%  Admixture max. 5% - Minerals max 0.5%.',
        photo: 'https://i.ibb.co/nw1LSRy/Calendula1.png',
        image: 'https://i.ibb.co/6YH8pJm/Calendula2.png'
    },
    {
        id: '3',
        category: 'Herbs',
        name:'Chamomile',
        color: 'yellow ',
        originOfBasil: 'Egypt',
        Type: '  conventional chamomile and organic chamomile .',
        harvestSeason: 'January To May',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'purity : 98 - 99%',
        Moisture: 'Moisture 5% Max.',
        Usage: 'Part use: lowers, petal, tea bag cut, pollen   ',
        feet: '20 ft container load of chamomile :3.5 ton - 40 ft container load of chamomile :7 ton ',
        description:'Chamomile is applied to the skin and mucous membrane for inflammations and skin diseases and Chamomile has been used as a tea for various conditions and as a topical cream.',
        photo: 'https://i.ibb.co/09wPGmB/camomile-PNG676.png',
        image: 'https://i.ibb.co/4VHfVXy/chamomile.png'
    },
    {
        id: '4',
        category: 'Herbs',
        name:'Coriander Leaves',
        color: 'green  ',
        originOfBasil: 'Egypt',
        Type: ' conventional coriander leaves and organic coriander leaves ',
        harvestSeason: ' Available throughout the year ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'tandard packages of coriander leaves 15 kg paper bag or pp bags  or as client request .%',
        Moisture: '8 - 10%max.',
        Usage: ' Part use: leaves - crushed, whole',
        feet: '20 ft container load of coriander leaves :5 ton  -  40 ft container load of coriander leaves :10 ton .',
        description:' People use the seed for medicine. Coriander is used for digestion problems including upset stomach, loss of appetite, hernia, nausea diarrhea, bowel spasms, and intestinal gas. It is also used to treat  measles, hemorrhoids, toothaches, worms, and joint pain, as well as infections caused by bacteria and fungus .',
        image: 'https://i.ibb.co/P9qrnQL/purepng-com-parsley-leavesfood-leaf-parsley-9415246383429y0vp.png',
        photo: 'https://i.ibb.co/991XNcP/purepng-com-parsley-leaffood-leaf-parsley-941524638572iyowc.png'
    },
    {
        id: '5',
        category: 'Herbs',
        name:'dill - Anethum graveolens',
        color: ' light green up to dark green ',
        originOfBasil: 'Egypt',
        Type: ' conventional dill and organic dill',
        harvestSeason: 'June to October  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical & Natural good smell',
        purity : ' Free of foreign matters -  Free of insects .',
        Moisture: 'Moisture max 5%',
        Usage: 'Part use: Leaves or partite or crushed or tips or seeds ',
        feet: ' 20 ft container load of dill :6 ton  -  40 ft container load of dill :12 ton .',
        description:' Dill is used for digestion problems including loss of appetite, intestinal gas Other uses for dill include treatment of fever and colds, cough, bronchitis ',
        photo: 'https://i.ibb.co/Kzt3bkf/Anethumgraveolens-Herb-Dill-Blue-Green-Leaves-Bright-Yellow-Flowers-and-Golden-Seeds-on-a-Kitchen-Su.png',
        image: 'https://i.ibb.co/L1x2g9G/dill-png-clip-art-11546980497pdijkzqxi4.png'
    },
    {
        id: '6',
        category: 'Herbs',
        name:' Hibiscus Sabdariffa',
        color: ' red ',
        originOfBasil: 'Egypt',
        Type: ' conventional hibiscus and organic hibiscus ',
        harvestSeason: ' Oct - May /  Available All year ',
        SmellAndTaste : ' aromatic, typical & Natural good smell',
        purity : 'standard packages of hibiscus: 10 kg carton box or 25kg',
        Moisture: 'Moisture max 12%',
        Usage: 'Part use: flowers,  petal,  tea bag cut , powder.',
        feet: ' 20 ft container load of hibiscus :3.5 ton - 40 ft container load of hibiscus :7 ton .',
        description:'uses of hibiscus: herbs, Medicinal plants, herbal tea, ingredients, flavor . ',
        photo: 'https://i.ibb.co/yFN4Pkk/unnamed.jpg',
        image: 'https://i.ibb.co/ZGmKTtx/16509857-hibiscus-sabdariffa-or-roselle-fruits-isolated-on-white-background.jpg'
    },
    {
        id: '7',
        category: 'Herbs',
        name:'Lemon Grass',
        color: ' light green up to  yellow ',
        originOfBasil: 'Egypt',
        Type: 'conventional lemon grass and organic lemon grass',
        harvestSeason: ' Apr - Dec / Availability: All year',
        SmellAndTaste : ' aromatic, typical',
        purity : 'purity 99%',
        Moisture: 'standard packages of lemon grass 10kg in carton box  or 20 paper bag or pp   bags  or as client request ',
        Usage: 'Part use: grass. 5 mm, 10 mm',
        feet: ' 20 ft container load of lemon grass :6 ton - 40 ft container load of lemon grass :12 ton',
        description:'uses of lemon grass: herbs , Medicinal plants , herbal tea, ingredients, Seasonings, flavor, spices ,It is also used to kill germs and as a mild astringent. Some people apply lemongrass and its essential oil directly to the skin for headache, stomachache, abdominal pain, and muscle pain. By inhalation, the essential oil of lemongrass is used as aromatherapy for muscle pain . ',
        image: 'https://i.ibb.co/VMmyYxD/loose-leaf-herbal-tea-sweet-lemongrass-1-5e20dfb9-3a54-43a0-8637-257f420e7954-860x.png',
        photo: 'https://i.ibb.co/pQyb4ck/HTB1kf-RSd-HSYBu-Nj-Sspi760-Nzp-Xa-S.png'
    },
    {
        id: '8',
        category: 'Herbs',
        name:'Origanum Majorana',
        color: 'green, gray',
        originOfBasil: 'Egypt',
        Type: 'conventional marjoram and organic marjoram',
        harvestSeason: 'May - Dec/ Availability: All year',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Purity : 99%, and Free of F.M' ,
        Moisture: 'Moisture max 10% - Stem max. 10% - F.M. max 2% ',
        Usage: 'Part use: leaves or crushed',
        feet: '20 ft container load of Majorana :6 ton - 40 ft container load of Majorana :12 ton .',
        description:' Uses  of marjoram: herbs, Medicinal plants, herbal tea, ingredients, Seasonings, flavor, spices, People make medicine from marjoram’s flowers, leaves, and oil. Marjoram is commonly used for runny nose, coughs, colds, infections, and various digestion problems and marjoram  oil are used as flavorings  .',
        image: 'https://i.ibb.co/cLs9yNc/marjoram.jpg',
        photo: 'https://i.ibb.co/jzwX7WP/Marjoram-2017-4-copy.jpg'
    },
    {
        id: '9',
        category: 'Herbs',
        name:' Moringa oleifera',
        color: 'green',
        originOfBasil: 'Egypt',
        Type: 'conventional moringa and organic moringa ',
        harvestSeason: ' Available throughout the year',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Moringa Leaves 30% Stem',
        Moisture: 'standard packages of moringa: 15 kg pp bags, 10 kg paper bags.',
        Usage: ' Part use: leaves, crushed, Moringa seeds',
        feet: '20 ft container load of Moringa :6 ton - 40 ft container load of Moringa :12 ton .',
        description:'uses of moringa , uses aromatic , herbal tea, ingredients, Seasonings, flavor, spices.',
        image: 'https://i.ibb.co/PxWsKP0/173-1731947-drumstick-vegetable-png-moringa-oleifera-transparent-png.png',
        photo: 'https://i.ibb.co/PxWsKP0/173-1731947-drumstick-vegetable-png-moringa-oleifera-transparent-png.png'
    },
    {
        id: '10',
        category: 'Herbs',
        name:'Origanum vulgare',
        color: ' Impurities max 2% - Total ash max 12% ',
        originOfBasil: 'Egypt',
        Type: 'Insoluble ash in HCl 10% max 2%',
        harvestSeason: 'June to October  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Packing:	POLYPROPYLENE, PAPER & CARTON, BAGS: 5 - 25 kg',
        Moisture: 'Moisture max 10%',
        Usage: 'Part use: leaves, crushed, Moringa seeds. ',
        feet: '20 ft container load of Origanum :6 ton - 40 ft container load of Origanum :12 ton .',
        description:' Oregano is scientifically known as Origanum vulgare and belongs to the mint family (Lamiaceae). In Greek, oregano is called “joy of the mountains.” It is also known as wild marjoram. The oregano plant is a perennial which grows up to two feet.',
        image: 'https://i.ibb.co/X83DD3r/dry-oregano.png',
        photo: 'https://i.ibb.co/sQ2cb5D/Origanum-6037-Edit-copy.jpg'
    },

    {
        id: '11',
        category: 'Herbs',
        name:'Parsley',
        color: 'light green up to dark green',
        originOfBasil: 'Egypt',
        Type: 'conventional parsley and organic parsley',
        harvestSeason: 'Jan - Jun / Availability: All year',
        SmellAndTaste : 'Good smell and  taste.',
        purity : 'purity 99% - Free of F.M and Free of infections. ',
        Moisture: 'Moisture 8 - 10%max.',
        Usage: 'Part use:leaves crushed, whole',
        feet: '20 ft container load of parsley :6 ton - 40 ft container load of parsley :12 ton .',
        description:'Parsley leaves and roots are popular as condiments worldwide, it is very popular, Parsley has been used as a source of vitamins and minerals, it is amazing herb .',
        image: 'https://i.ibb.co/W5ZhfjZ/pngtree-fresh-coriander-green-leaf-realistic-parsley-png-image-3688072.jpg',
        photo: 'https://i.ibb.co/991XNcP/purepng-com-parsley-leaffood-leaf-parsley-941524638572iyowc.png'
    },
    {
        id: '12',
        category: 'Herbs',
        name:'Peppermint',
        color: ' Dark green ',
        originOfBasil: 'Egypt',
        Type: 'conventional peppermint and organic peppermint',
        harvestSeason: 'May - Dec/ Availability: All year',
        SmellAndTaste : 'Good smell.',
        purity : 'Limited pesticides Free of insects.',
        Moisture: 'Grade No. 1, size 5 . 6 mm, moisture max 10%, oil min 1%',
        Usage: ' Part use: leaves crushed, whole, TBC',
        feet: '20 ft container load of peppermint :5 ton - 40 ft container load of peppermint :10 ton .',
        description:'  Uses of peppermint: herbs , Medicinal plants , aromatic , herbal tea, ingredients, Seasonings, flavor, spices, Peppermint is used to add flavor or fragrance to foods, cosmetics, soaps, toothpastes, mouthwashes, and other products like herbal tea, and it may have some medicinal uses .',
        image: 'https://i.ibb.co/py6GJH5/240-2403086-peppermint-png-pic-peppermint-png.png',
        photo: 'https://i.ibb.co/py6GJH5/240-2403086-peppermint-png-pic-peppermint-png.png'
    },
    {
        id: '13',
        category: 'Herbs',
        name:'Sage',
        color: 'Light gray ',
        originOfBasil: 'Egypt',
        Type: ' conventional basil  and  organic sage .',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity : 99%',
        Moisture: 'standard packages of sage: 20 kg pp bags, 10 kg carton box.',
        Usage: 'Part use: leavesWhole , Crushed , TBC, and powder',
        feet: '20 ft container load of sage :6 ton - 40 ft container load of sage :12 ton .',
        description:'Sage is used for digestive problems, including loss of appetite, gas flatulence), stomach pain (gastritis), diarrhea, bloating, and  heartburn. It is also used for reducing overproduction of perspiration and saliva; and for depression, memory loss, and Alzheimer’s disease . ',
        photo: 'https://i.ibb.co/ZfXbVz3/211-2111187-sage-herb-sage-hd-png-download.png',
        image: 'https://i.ibb.co/vQ6LSd7/sage-sage-11563227008y9ia1tkdvx.png'
    },
    {
        id: '14',
        category: 'Herbs',
        name:'Spearmint',
        color: 'green  ',
        originOfBasil: 'Egypt',
        Type: ' conventional Spearmint  and  organic  .',
        harvestSeason: 'Mar - Dec and  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'standard packages of spearmint: 20 kg PP bags , PAPER & CARTON BAGS .',
        Usage: 'Part use: leaves crushed, whole, TBC',
        feet: '20 ft container load of Spearmint :6 ton - 40 ft container load of Spearmint :11 ton .',
        description:'  uses of spearmint: herbs , Medicinal plants , aromatic , herbal tea, ingredients, Seasonings, flavor, spices . ',
        image: 'https://i.ibb.co/YNcmvLk/kisspng-peppermint-essential-oil-spearmint-lekarnar-com-sp-midori-cannabis-infused-breath-strips-fre.jpg',
        photo: 'https://i.ibb.co/M92P4j6/png-transparent-green-herbal-plant-mentha-spicata-peppermint-maghrebi-mint-tea-mentha-longifolia-min.png'
    },
]
export default HerbsAPI