const Data =[
    {
        id: '1',
        category: 'Herbs',
        name:'Basil',
        color: 'green – brown ',
        originOfBasil: 'Egypt',
        Type: ' conventional basil  and  organic basil .',
        harvestSeason: 'June to October  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'purity 99%',
        Moisture: 'Moisture 8 - 10%max.',
        Usage: 'herbs , Medicinal plants , aromatic , herbal tea, Seasonings, flavor, spices, dried vegetables . ',
        feet: '20 ft container load of basil :6 ton - 40 ft container load of basil :11 ton .',
        description:' Same smell of the fresh basil. Free of alive or dead insects Free of mouldy or bad smell, Moisture  8 - 10%max Vaporous oil min. 0.3%',
        image: '/assets/Basil.png',
        photo: '/assets/bsil2.png'
    },
    {
        id: '2',
        category: 'Herbs',
        name:'Calendula – Marigold',
        color: ' Orange  ',
        originOfBasil: 'Egypt',
        Type: 'Foreign Materials or Ash 0% ',
        harvestSeason:  'conventional calendula, marigold and organic calendula, marigold. ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'purity 99%',
        Moisture: 'Moisture max 5-10%.',
        Usage: 'Part use: flowers, petal, tea bag cut',
        feet: '20 ft container load of calendula, marigold :4 ton - 40 ft container load of calendula, marigold :  8 ton.  ',
        description:' Calendula, marigold is applied to the skin and mucous membrane for inflammations and skin diseases  Calendula, marigold has been used as a tea for various conditions and as a topical cream .Stem & bells max 3%  Admixture max. 5% - Minerals max 0.5%.',
        image: '/assets/Calendula.png',
        photo: '/assets/Calendula4.png'
    },
    {
        id: '3',
        category: 'Herbs',
        name:'Chamomile',
        color: 'yellow ',
        originOfBasil: 'Egypt',
        Type: '  conventional chamomile and organic chamomile .',
        harvestSeason: 'January To May',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'purity : 98 - 99%',
        Moisture: 'Moisture 5% Max.',
        Usage: 'Part use: lowers, petal, tea bag cut, pollen   ',
        feet: '20 ft container load of chamomile :3.5 ton - 40 ft container load of chamomile :7 ton ',
        description:'Chamomile is applied to the skin and mucous membrane for inflammations and skin diseases and Chamomile has been used as a tea for various conditions and as a topical cream.',
        image: '/assets/chamomile.png',
        photo: '/assets/chamomile.png'
    },
    {
        id: '4',
        category: 'Herbs',
        name:'Coriander Leaves',
        color: 'green  ',
        originOfBasil: 'Egypt',
        Type: ' conventional coriander leaves and organic coriander leaves ',
        harvestSeason: ' Available throughout the year ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'tandard packages of coriander leaves 15 kg paper bag or pp bags  or as client request .%',
        Moisture: '8 - 10%max.',
        Usage: ' Part use: leaves - crushed, whole',
        feet: '20 ft container load of coriander leaves :5 ton  -  40 ft container load of coriander leaves :10 ton .',
        description:' People use the seed for medicine. Coriander is used for digestion problems including upset stomach, loss of appetite, hernia, nausea diarrhea, bowel spasms, and intestinal gas. It is also used to treat  measles, hemorrhoids, toothaches, worms, and joint pain, as well as infections caused by bacteria and fungus .',
        image: '/assets/corianderleavs.png',
        photo: '/assets/corianderleavs.png'
    },
    {
        id: '5',
        category: 'Herbs',
        name:'dill - Anethum graveolens',
        color: ' light green up to dark green ',
        originOfBasil: 'Egypt',
        Type: ' conventional dill and organic dill',
        harvestSeason: 'June to October  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical & Natural good smell',
        purity : ' Free of foreign matters -  Free of insects .',
        Moisture: 'Moisture max 5%',
        Usage: 'Part use: Leaves or partite or crushed or tips or seeds ',
        feet: ' 20 ft container load of dill :6 ton  -  40 ft container load of dill :12 ton .',
        description:' Dill is used for digestion problems including loss of appetite, intestinal gas Other uses for dill include treatment of fever and colds, cough, bronchitis ',
        image: '/assets/dill.png',
        photo: '/assets/dill2.png'
    },
    {
        id: '6',
        category: 'Herbs',
        name:' Hibiscus Sabdariffa',
        color: ' red ',
        originOfBasil: 'Egypt',
        Type: ' conventional hibiscus and organic hibiscus ',
        harvestSeason: ' Oct - May /  Available All year ',
        SmellAndTaste : ' aromatic, typical & Natural good smell',
        purity : 'standard packages of hibiscus: 10 kg carton box or 25kg',
        Moisture: 'Moisture max 12%',
        Usage: 'Part use: flowers,  petal,  tea bag cut , powder.',
        feet: ' 20 ft container load of hibiscus :3.5 ton - 40 ft container load of hibiscus :7 ton .',
        description:'uses of hibiscus: herbs, Medicinal plants, herbal tea, ingredients, flavor . ',
        image: '/assets/Hibiscus.png',
        photo: '/assets/Hibiscus2.png'
    },
    {
        id: '7',
        category: 'Herbs',
        name:'Lemon Grass',
        color: ' light green up to  yellow ',
        originOfBasil: 'Egypt',
        Type: 'conventional lemon grass and organic lemon grass',
        harvestSeason: ' Apr - Dec / Availability: All year',
        SmellAndTaste : ' aromatic, typical',
        purity : 'purity 99%',
        Moisture: 'standard packages of lemon grass 10kg in carton box  or 20 paper bag or pp   bags  or as client request ',
        Usage: 'Part use: grass. 5 mm, 10 mm',
        feet: ' 20 ft container load of lemon grass :6 ton - 40 ft container load of lemon grass :12 ton',
        description:'uses of lemon grass: herbs , Medicinal plants , herbal tea, ingredients, Seasonings, flavor, spices ,It is also used to kill germs and as a mild astringent. Some people apply lemongrass and its essential oil directly to the skin for headache, stomachache, abdominal pain, and muscle pain. By inhalation, the essential oil of lemongrass is used as aromatherapy for muscle pain . ',
        image: '/assets/lemongrass.png',
        photo: '/assets/lemongrass2.png'
    },
    {
        id: '8',
        category: 'Herbs',
        name:'Origanum Majorana',
        color: 'green, gray',
        originOfBasil: 'Egypt',
        Type: 'conventional marjoram and organic marjoram',
        harvestSeason: 'May - Dec/ Availability: All year',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Purity : 99%, and Free of F.M' ,
        Moisture: 'Moisture max 10% - Stem max. 10% - F.M. max 2% ',
        Usage: 'Part use: leaves or crushed',
        feet: '20 ft container load of Majorana :6 ton - 40 ft container load of Majorana :12 ton .',
        description:' Uses  of marjoram: herbs, Medicinal plants, herbal tea, ingredients, Seasonings, flavor, spices, People make medicine from marjoram’s flowers, leaves, and oil. Marjoram is commonly used for runny nose, coughs, colds, infections, and various digestion problems and marjoram  oil are used as flavorings  .',
        image: '/assets/marjoram.png',
        photo: '/assets/marjoram.png'
    },
    {
        id: '9',
        category: 'Herbs',
        name:' Moringa oleifera',
        color: 'green',
        originOfBasil: 'Egypt',
        Type: 'conventional moringa and organic moringa ',
        harvestSeason: ' Available throughout the year',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Moringa Leaves 30% Stem',
        Moisture: 'standard packages of moringa: 15 kg pp bags, 10 kg paper bags.',
        Usage: ' Part use: leaves, crushed, Moringa seeds',
        feet: '20 ft container load of Moringa :6 ton - 40 ft container load of Moringa :12 ton .',
        description:'uses of moringa , uses aromatic , herbal tea, ingredients, Seasonings, flavor, spices.',
        image: '/assets/Moringa.png',
        photo: '/assets/Moringa2.png'
    },
    {
        id: '10',
        category: 'Herbs',
        name:'Origanum vulgare',
        color: ' Impurities max 2% - Total ash max 12% ',
        originOfBasil: 'Egypt',
        Type: 'Insoluble ash in HCl 10% max 2%',
        harvestSeason: 'June to October  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Packing:	POLYPROPYLENE, PAPER & CARTON, BAGS: 5 - 25 kg',
        Moisture: 'Moisture max 10%',
        Usage: 'Part use: leaves, crushed, Moringa seeds. ',
        feet: '20 ft container load of Origanum :6 ton - 40 ft container load of Origanum :12 ton .',
        description:' Oregano is scientifically known as Origanum vulgare and belongs to the mint family (Lamiaceae). In Greek, oregano is called “joy of the mountains.” It is also known as wild marjoram. The oregano plant is a perennial which grows up to two feet.',
        image: '/assets/oregano.png',
        photo: '/assets/oregano2.png'
    },

    {
        id: '11',
        category: 'Herbs',
        name:'Parsley',
        color: 'light green up to dark green',
        originOfBasil: 'Egypt',
        Type: 'conventional parsley and organic parsley',
        harvestSeason: 'Jan - Jun / Availability: All year',
        SmellAndTaste : 'Good smell and  taste.',
        purity : 'purity 99% - Free of F.M and Free of infections. ',
        Moisture: 'Moisture 8 - 10%max.',
        Usage: 'Part use:leaves crushed, whole',
        feet: '20 ft container load of parsley :6 ton - 40 ft container load of parsley :12 ton .',
        description:'Parsley leaves and roots are popular as condiments worldwide, it is very popular, Parsley has been used as a source of vitamins and minerals, it is amazing herb .',
        image: '/assets/Parsley.png',
        photo: '/assets/Parsley.png'
    },
    {
        id: '12',
        category: 'Herbs',
        name:'Peppermint',
        color: ' Dark green ',
        originOfBasil: 'Egypt',
        Type: 'conventional peppermint and organic peppermint',
        harvestSeason: 'May - Dec/ Availability: All year',
        SmellAndTaste : 'Good smell.',
        purity : 'Limited pesticides Free of insects.',
        Moisture: 'Grade No. 1, size 5 . 6 mm, moisture max 10%, oil min 1%',
        Usage: ' Part use: leaves crushed, whole, TBC',
        feet: '20 ft container load of peppermint :5 ton - 40 ft container load of peppermint :10 ton .',
        description:'  Uses of peppermint: herbs , Medicinal plants , aromatic , herbal tea, ingredients, Seasonings, flavor, spices, Peppermint is used to add flavor or fragrance to foods, cosmetics, soaps, toothpastes, mouthwashes, and other products like herbal tea, and it may have some medicinal uses .',
        image: '/assets/PEPPERMINT.png',
        photo: '/assets/PEPPERMINT2.png'
    },
    {
        id: '13',
        category: 'Herbs',
        name:'Sage',
        color: 'Light gray ',
        originOfBasil: 'Egypt',
        Type: ' conventional basil  and  organic sage .',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity : 99%',
        Moisture: 'standard packages of sage: 20 kg pp bags, 10 kg carton box.',
        Usage: 'Part use: leavesWhole , Crushed , TBC, and powder',
        feet: '20 ft container load of sage :6 ton - 40 ft container load of sage :12 ton .',
        description:'Sage is used for digestive problems, including loss of appetite, gas flatulence), stomach pain (gastritis), diarrhea, bloating, and  heartburn. It is also used for reducing overproduction of perspiration and saliva; and for depression, memory loss, and Alzheimer’s disease . ',
        image: '/assets/Sage2.png',
        photo: '/assets/Sage2.png'
    },
    {
        id: '14',
        category: 'Herbs',
        name:'Spearmint',
        color: 'green  ',
        originOfBasil: 'Egypt',
        Type: ' conventional Spearmint  and  organic  .',
        harvestSeason: 'Mar - Dec and  Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'standard packages of spearmint: 20 kg PP bags , PAPER & CARTON BAGS .',
        Usage: 'Part use: leaves crushed, whole, TBC',
        feet: '20 ft container load of Spearmint :6 ton - 40 ft container load of Spearmint :11 ton .',
        description:'  uses of spearmint: herbs , Medicinal plants , aromatic , herbal tea, ingredients, Seasonings, flavor, spices . ',
        image: '/assets/Spearmintяяя.png',
        photo: '/assets/Spearmintяяя3.png'
    },
    {
        id: '15',
        category: 'Seeds',
        name:'Pimpinella Anisum',
        color: 'Brown',
        originOfBasil: 'Egypt',
        Type: ' conventional anise and organic.',
        harvestSeason: 'From May to Aug ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Purity 99%',
        Moisture: 'Moisture 8 - 10 %max.',
        Usage: 'Part use: leaves crushed, whole, TBC',
        feet: '20 ft container load of anise :12.5 ton - 40 ft container load of anise :25 ton .',
        description:'Anise is used for upset stomach, intestinal gas, “runny nose” and as an   expectorant to increase productive cough, as a diuretic to increase urine flow.',
        image: '/assets/aniseseeds.png',
        photo: '/assets/aniseseeds.png'
    },

    {
        id: '16',
        category: 'Seeds',
        name:'caraway seeds',
        color: 'Dark Brown',
        originOfBasil: 'Egypt',
        Type: ' conventional caraway seeds and organic caraway seeds.',
        harvestSeason: 'May – Dec Available throughout the year ',
        SmellAndTaste : ' Good color & smell without mould or bad smell',
        purity : 'Purity 99% - Admixture Max. 3%',
        Moisture: ' Moisture Max. 10% ',
        Usage: 'Seeds',
        description: 'uses caraway seeds: herbs , Medicinal plants , aromatic , herbal tea, ingredients, Seasonings, flavor, spices, Caraway is used for digestive problems including heartburn, bloating, gas, loss   of appetite, and mild spasms of the stomach and intestines. Caraway oil is also used to help people cough up phlegm, improve control of urination, kill bacteria in the body, and relieve constipation. .',
        feet:'20 ft container load of caraway :12 ton - 40 ft container load of caraway :25 ton .',
        image: '/assets/dill2.png',
        photo: '/assets/dill2.png'
    },
    {
        id: '17',
        category: 'Seeds',
        name:'Cumin Seeds',
        color: 'Green cumin – brown cumin – black cumin',
        originOfBasil: 'Egypt',
        Type: 'Grade: TOP GRADE',
        harvestSeason: 'Aug - Dec, Availability: All year',
        SmellAndTaste : 'Size: Depend on Customers Needs',
        purity : 'Purity 99%',
        Moisture: 'Moisture 5 - 10% max.',
        Usage: 'Seeds',
        feet: '20 ft container load of Cumin :12 ton - 40 ft container load of Cumin :25 ton .',
        description:' Packing: 25 kg in paper bag or pp bags  or as client request .',
        image: '/assets/cumin.png',
        photo: '/assets/cumin.png'
    },

    {
        id: '18',
        category: 'Fennel Seeds',
        name:'Pimpinella Anisum',
        color: 'major green and some brown',
        originOfBasil: 'Egypt',
        Type: ' conventional fennel and organic fennel.',
        harvestSeason: 'Jun - Dec / Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'Humidity 5% - 10% max.',
        Usage: 'Seeds',
        feet: '20 ft container load of Fennel :15 ton - 40 ft container load of Fennel :25 ton .',
        description:'  uses, fennel and its seeds offer a wide array of health benefits and may provide antioxidant, anti-inflammatory. used to treat an array of digestive ailments, including heartburn .',
        image: '/assets/fennel1.png',
        photo: '/assets/fennel.png'
    },
    {
        id: '19',
        category: 'Seeds',
        name:'Fenugreek',
        color: 'green fenugreek and yellow fenugreek',
        originOfBasil: 'Egypt',
        Type: ' conventional fenugreek and organic fenugreek.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99% and Well cleaned.',
        Moisture: 'Moisture max. 12% - Oil min 1%',
        Usage: 'Seeds',
        feet: '20 ft container load of fenugreek :15 ton - 40 ft container load of fenugreek :25 ton .',
        description:'uses of fenugreek seeds: herbs , Medicinal plants , aromatic , herbal tea,  spices, Fenugreek seeds are rich source of gum, fiber, alkaloid, flavonoids, saponin and...., potential applications of fenugreek as a functional food and nutraceutical.',
        image: '/assets/Fenugreek.png',
        photo: '/assets/Fenugreek3.png'
    },

    {
        id: '20',
        category: 'Seeds',
        name:'Sesame',
        color: 'Golden - White',
        originOfBasil: 'Egypt',
        Type: 'Quality: COLOR  SORTEX  CLEANED',
        harvestSeason: ' FREE OF SMELL BAD.  ',
        SmellAndTaste : 'STEM AND SEED MAX. 0.3%. ',
        purity : 'Purity 98% - 99%',
        Moisture: 'Moisture:  8 % Maximum',
        Usage: 'Seeds',
        feet: 'CONTAINER CAPACITY19 ton/ 20 FCL',
        description:' Packing:	PP bags  & PAPER BAGS 25 kg',
        image: '/assets/dill2.png',
        photo: '/assets/dill2.png'
    },
    {
        id: '21',
        category: 'Spices',
        name:'Coriander seeds',
        color: 'Yellowish brown or light brown.',
        originOfBasil: 'Egypt',
        Type: ' conventional anise and organic basil.',
        harvestSeason: ' Jun – Oct /  Available throughout the year ',
        SmellAndTaste : ' Good color, smell and taste.',
        purity : 'Purity 99% - broken seeds max.3%',
        Moisture: 'Moisture 5% - 10% max.',
        Usage: 'Free of alive or dead insects or rodents.',
        feet: '20 ft container load of Coriander :6 ton - 40 ft container load of Coriander :11 ton .',
        description:'Packing in 25 kg paper bag or pp  bags  or as client request .',
        image: '/assets/sesame2.png',
        photo: '/assets/sesame3.png'
    },
    {
        id: '22',
        category: 'Seeds',
        name:'Dried Lemon',
        color: 'yellow Or black',
        originOfBasil: 'Egypt',
        Type: 'Size Range : 2.5 cm to 4.0 cm.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'Moisture 7% - 10% max.',
        Usage: 'Spices',
        feet: '20 ft container load of dried lemon  :5 ton - 40 ft container load of dried lemon  :10 ton .',
        description:'',
        image: '/assets/dill2.png',
        photo: '/assets/dill2.png'
    },
    {
        id: '23',
        category: 'Spices',
        name:'Molokhia',
        color: ' Dark green',
        originOfBasil: 'Egypt',
        Type: 'size 5.6mm',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'free of insects',
        Moisture: 'Moisture  max 13%. - oil min 1%,',
        Usage: 'Part use: leaves,crushed',
        feet: 'Molokhia leaves, 1.5 ton/20 fcl - Molokhia leaves, 3 ton /40 fcl.',
        description:'Packing in Carton box 5 Kg per bag.',
        image: '/assets/Molokhya.png',
        photo: '/assets/Molokhya1.png'
    },
    {
        id: '24',
        category: 'Spices',
        name:' Red Chili',
        color: 'red',
        originOfBasil: 'Egypt',
        Type: 'Size: Depend on Customers Needs',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : 'Grade:TOP GRADE',
        purity : 'Purity: High',
        Moisture: 'Moisture 5% max.',
        Usage: 'Foreign Materials:No Foreign Materials or Ash 0',
        feet: '6 ton / 20FCL - 12 ton / 40FCL.',
        description:' Used: Culinary, Medicinal ,flavor , industry & Tea',
        image: '/assets/redChili.png',
        photo: '/assets/redChili2.png'
    }, 
    {
        id: '25',
        category: 'Spices',
        name:'Rosemary',
        color: 'green',
        originOfBasil: 'Egypt',
        Type: ' conventional rosemary and organic rosemary.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Grade: TOP GRADE ',
        Moisture: 'Moisture 5% max.',
        Usage: 'Spices',
        feet: '20 ft container load of rosemary :6 ton - 40 ft container load of rosemary :12 ton .',
        description:'Description :Drying Process :"SD" Sun dried - Size: Depend on Customers Needs - Aroma: Pungent Sweet -  Flavor:Characteristic flavor',
        image: '/assets/rosmary.png',
        photo: '/assets/rosmary.png'
    },
    {
        id: '26',
        category: 'Spices',
        name:'Thyme',
        color: 'green',
        originOfBasil: 'Egypt',
        Type: ' conventional anise and organic basil.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99% and Admixture 1% ',
        Moisture: 'Moisture 5%.',
        Usage: 'Part use:  thyme',
        feet: '20 ft container load of Thyme :7 ton - 40 ft container load of Thyme :14 ton .',
        description:' uses Thyme is by mouth for bronchitis, whooping cough, sore throat, colic, arthritis, upset stomach, stomach pain gastritis, diarrhea, bedwetting, a movement disorder in children dyspraxia, intestinal gas flatulence, parasitic worm infections, and skin disorders .',
        image: '/assets/thyme3.png',
        photo: '/assets/thyme.png'
    },
    {
        id: '27',
        category: 'Dried Tomatos',
        name:'Pimpinella',
        color: 'red',
        originOfBasil: 'Egypt',
        Type: 'Ingredients: Tomatoes, Salt, citric, ascorbic acid.',
        harvestSeason: '  Flavour: Characteristic of tomato without off tasted ',
        SmellAndTaste : ' aromatic, typical.',
        purity : ' Storage Conditions: Store in dry hygienic place at +3° C',
        Moisture: 'Tomatoes out off colour uniformity Max. 2%',
        Usage: 'Cut 10X10mm in case of dried',
        feet: ' Packing : boxes In Carton10 k.g',
        description:'  Chemical Specification : Moisture Content 10-14% Incase of Dried Tomato 6% Salt Ratio max. 8-9%',
        image: '/assets/DriedTomotes2.png',
        photo: '/assets/DriedTomotes.png'
    },
    {
        id: '28',
        category: 'Special Product',
        name:'garlic',
        color: ' red & white ',
        originOfBasil: 'Egypt',
        Type: ' conventional garlic and organic garlic.',
        harvestSeason: 'fresh from  January to Mar and  Dry from April to Sep . ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'Packing:  5 kg   -  10kg Mesh bags and   carton box  or as customer request ',
        Usage: 'Special Product',
        feet: 'Sizes: 3-4cm, 4cm, 5cm, 5.5cm, 6cm, 6.5cm and up to 8 cm',
        description:'Length: 2, 5, 8, 10, 12, 15, 20 cm .',
        image: '/assets/Garlic.png',
        photo: '/assets/Garlic2.png'
    },
    {
        id: '30',
        category: 'Special Product',
        name:'onion',
        color: ' Red and Yellow',
        originOfBasil: 'Egypt',
        Type: 'Fresh Onion Class A Egyptian',
        harvestSeason: 'Carbon percentage :  5 % max',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Size: 1.5  -  13cm as required .',
        Moisture: '  Packaging :  2  , 5 , 7 , 10 , 15 , 20 , 25 , 50 kg .',
        Usage: 'Special Product',
        feet: 'Container 40 feet Capacity 25 tons .',
        description:'',
        image: '/assets/onion2.png',
        photo: '/assets/onion3.png'
    },    
]

export default Data

//     {
//         id: '2',
//         category: 'Special Product',
//         name:'Pimpinella',
//         color: 'Brown',
//         originOfBasil: 'Egypt',
//         Type: ' conventional anise and organic basil.',
//         harvestSeason: 'Available throughout the year ',
//         SmellAndTaste : ' aromatic, typical.',
//         purity : 'Purity 99%',
//         Moisture: 'Moisture 8% - 10% max.',
//         Usage: 'Spices',
//         feet: '20 ft container load of basil :6 ton - 40 ft container load of basil :11 ton .',
//         description:'',
//         image: '/assets/dill2.png',
//         photo: '/assets/dill2.png'
//    },
