const SpecialProductsAPI =[
    {
        id: '27',
        category: 'Special Product',
        name:'Dried Tomatoes',
        color: 'red',
        originOfBasil: 'Egypt',
        Type: 'Ingredients: Tomatoes, Salt, citric, ascorbic acid.',
        harvestSeason: '  Flavour: Characteristic of tomato without off tasted ',
        SmellAndTaste : ' aromatic, typical.',
        purity : ' Storage Conditions: Store in dry hygienic place at +3° C',
        Moisture: 'Tomatoes out off colour uniformity Max. 2%',
        Usage: 'Cut 10X10mm in case of dried',
        feet: ' Packing : boxes In Carton10 k.g',
        description:'  Chemical Specification : Moisture Content 10-14% Incase of Dried Tomato 6% Salt Ratio max. 8-9%',
        photo: 'https://i.ibb.co/bLrj7m5/Sun-Dried-Tomatoes.png',
        image: 'https://i.ibb.co/g9Dbg2R/scarlatto-red-pomodori-2016.png'
    },
    {
        id: '28',
        category: 'Special Product',
        name:'garlic',
        color: ' red & white ',
        originOfBasil: 'Egypt',
        Type: ' conventional garlic and organic garlic.',
        harvestSeason: 'fresh from  January to Mar and  Dry from April to Sep . ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'Packing:  5 kg   -  10kg Mesh bags and   carton box  or as customer request ',
        Usage: 'Special Product',
        feet: 'Sizes: 3-4cm, 4cm, 5cm, 5.5cm, 6cm, 6.5cm and up to 8 cm',
        description:'Length: 2, 5, 8, 10, 12, 15, 20 cm .',
        photo: 'https://i.ibb.co/x5Xkznc/8721f5869b6a260d84d9b0b5a7e469a6.jpg',
        image: 'https://i.ibb.co/cLWYpR9/purepng-com-garlicgarlicwhite-garlicrecepie-1701527256150ns7cx.png'
    },
    {
        id: '30',
        category: 'Special Product',
        name:'onion',
        color: ' Red and Yellow',
        originOfBasil: 'Egypt',
        Type: 'Fresh Onion Class A Egyptian',
        harvestSeason: 'Carbon percentage :  5 % max',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Size: 1.5  -  13cm as required .',
        Moisture: '  Packaging :  2  , 5 , 7 , 10 , 15 , 20 , 25 , 50 kg .',
        Usage: 'Special Product',
        feet: 'Container 40 feet Capacity 25 tons .',
        description:'',
        image: 'https://i.ibb.co/Xpy9YC9/unnamed.png',
        photo: 'https://i.ibb.co/4PV7dms/images.jpg'
    },
]
export default SpecialProductsAPI