const SeedsAPI =[
    {
        id: '15',
        category: 'Seeds',
        name:'Pimpinella Anisum',
        color: 'Brown',
        originOfBasil: 'Egypt',
        Type: ' conventional anise and organic.',
        harvestSeason: 'From May to Aug ',
        SmellAndTaste : ' aromatic, typical .',
        purity : 'Purity 99%',
        Moisture: 'Moisture 8 - 10 %max.',
        Usage: 'Part use: leaves crushed, whole, TBC',
        feet: '20 ft container load of anise :12.5 ton - 40 ft container load of anise :25 ton .',
        description:'Anise is used for upset stomach, intestinal gas, “runny nose” and as an   expectorant to increase productive cough, as a diuretic to increase urine flow.',
        image: 'https://i.ibb.co/N9K6zSJ/Anise-1024x1024-2x.png',
        photo: 'https://i.ibb.co/N9K6zSJ/Anise-1024x1024-2x.png'
    },

    {
        id: '16',
        category: 'Seeds',
        name:'caraway seeds',
        color: 'Dark Brown',
        originOfBasil: 'Egypt',
        Type: ' conventional caraway seeds and organic caraway seeds.',
        harvestSeason: 'May – Dec Available throughout the year ',
        SmellAndTaste : ' Good color & smell without mould or bad smell',
        purity : 'Purity 99% - Admixture Max. 3%',
        Moisture: ' Moisture Max. 10% ',
        Usage: 'Seeds',
        description: 'uses caraway seeds: herbs , Medicinal plants , aromatic , herbal tea, ingredients, Seasonings, flavor, spices, Caraway is used for digestive problems including heartburn, bloating, gas, loss   of appetite, and mild spasms of the stomach and intestines. Caraway oil is also used to help people cough up phlegm, improve control of urination, kill bacteria in the body, and relieve constipation. .',
        feet:'20 ft container load of caraway :12 ton - 40 ft container load of caraway :25 ton .',
        photo: 'https://i.ibb.co/258G9m0/images.jpg',
        image: 'https://i.ibb.co/wzxRvsM/dill-cumin-spice-seed-fenugreek-others-png-clip-art.png'
    },
    {
        id: '17',
        category: 'Seeds',
        name:'Cumin Seeds',
        color: 'Green cumin – brown cumin – black cumin',
        originOfBasil: 'Egypt',
        Type: 'Grade: TOP GRADE',
        harvestSeason: 'Aug - Dec, Availability: All year',
        SmellAndTaste : 'Size: Depend on Customers Needs',
        purity : 'Purity 99%',
        Moisture: 'Moisture 5 - 10% max.',
        Usage: 'Seeds',
        feet: '20 ft container load of Cumin :12 ton - 40 ft container load of Cumin :25 ton .',
        description:' Packing: 25 kg in paper bag or pp bags  or as client request .',
        image: 'https://i.ibb.co/y5PPQXy/cumin-seeds-jeera-500x500-500x500.png',
        photo: 'https://i.ibb.co/y5PPQXy/cumin-seeds-jeera-500x500-500x500.png'
    },

    {
        id: '18',
        category: 'Fennel Seeds',
        name:'Pimpinella Anisum',
        color: 'major green and some brown',
        originOfBasil: 'Egypt',
        Type: ' conventional fennel and organic fennel.',
        harvestSeason: 'Jun - Dec / Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'Humidity 5% - 10% max.',
        Usage: 'Seeds',
        feet: '20 ft container load of Fennel :15 ton - 40 ft container load of Fennel :25 ton .',
        description:'  uses, fennel and its seeds offer a wide array of health benefits and may provide antioxidant, anti-inflammatory. used to treat an array of digestive ailments, including heartburn .',
        image: 'https://i.ibb.co/GxrFxgG/fennel-mukhwas-seed-cumin-spice-mustard-seed.jpg',
        photo: 'https://i.ibb.co/9vS0Q5Z/fennel-seed-1000x.png'
    },
    {
        id: '19',
        category: 'Seeds',
        name:'Fenugreek',
        color: 'green fenugreek and yellow fenugreek',
        originOfBasil: 'Egypt',
        Type: ' conventional fenugreek and organic fenugreek.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99% and Well cleaned.',
        Moisture: 'Moisture max. 12% - Oil min 1%',
        Usage: 'Seeds',
        feet: '20 ft container load of fenugreek :15 ton - 40 ft container load of fenugreek :25 ton .',
        description:'uses of fenugreek seeds: herbs , Medicinal plants , aromatic , herbal tea,  spices, Fenugreek seeds are rich source of gum, fiber, alkaloid, flavonoids, saponin and...., potential applications of fenugreek as a functional food and nutraceutical.',
        image: 'https://i.ibb.co/bWGVwGY/facts-about-fenugreek-theodore-medium-fenugreeks-png-562-410.png',
        photo: 'https://i.ibb.co/LvWfpW2/images.jpg'
    },

    {
        id: '20',
        category: 'Seeds',
        name:'Sesame',
        color: 'Golden - White',
        originOfBasil: 'Egypt',
        Type: 'Quality: COLOR  SORTEX  CLEANED',
        harvestSeason: ' FREE OF SMELL BAD.  ',
        SmellAndTaste : 'STEM AND SEED MAX. 0.3%. ',
        purity : 'Purity 98% - 99%',
        Moisture: 'Moisture:  8 % Maximum',
        Usage: 'Seeds',
        feet: 'CONTAINER CAPACITY19 ton/ 20 FCL',
        description:' Packing:	PP bags  & PAPER BAGS 25 kg',
        image: 'https://i.ibb.co/jLDpTL6/unnamed.png',
        photo: 'https://i.ibb.co/wwFC2s9/sesame-seeds-png-sesame-seeds-png-transparent-hd-images-sesame-png-427-413.png'
    },
    {
        id: '21',
        category: 'Spices',
        name:'Coriander seeds',
        color: 'Yellowish brown or light brown.',
        originOfBasil: 'Egypt',
        Type: ' conventional anise and organic basil.',
        harvestSeason: ' Jun – Oct /  Available throughout the year ',
        SmellAndTaste : ' Good color, smell and taste.',
        purity : 'Purity 99% - broken seeds max.3%',
        Moisture: 'Moisture 5% - 10% max.',
        Usage: 'Free of alive or dead insects or rodents.',
        feet: '20 ft container load of Coriander :6 ton - 40 ft container load of Coriander :11 ton .',
        description:'Packing in 25 kg paper bag or pp  bags  or as client request .',
        image: 'https://i.ibb.co/qYkGv3z/images.jpg',
        photo: 'https://i.ibb.co/CVhyLZM/dried-coriander-seeds-olive-wood-260nw-1041544780.jpg'
    },
    {
        id: '22',
        category: 'Seeds',
        name:'Dried Lemon',
        color: 'yellow Or black',
        originOfBasil: 'Egypt',
        Type: 'Size Range : 2.5 cm to 4.0 cm.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99%',
        Moisture: 'Moisture 7% - 10% max.',
        Usage: 'Spices',
        feet: '20 ft container load of dried lemon  :5 ton - 40 ft container load of dried lemon  :10 ton .',
        description:'',
        image: 'https://i.ibb.co/NxZpYQM/images-2.jpg',
        photo: 'https://i.ibb.co/NxZpYQM/images-2.jpg'
    },
]
export default  SeedsAPI