const SpicesAPI=[
    {
        id: '23',
        category: 'Spices',
        name:'Molokhia',
        color: ' Dark green',
        originOfBasil: 'Egypt',
        Type: 'size 5.6mm',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'free of insects',
        Moisture: 'Moisture  max 13%. - oil min 1%,',
        Usage: 'Part use: leaves,crushed',
        feet: 'Molokhia leaves, 1.5 ton/20 fcl - Molokhia leaves, 3 ton /40 fcl.',
        description:'Packing in Carton box 5 Kg per bag.',
        image: 'https://i.ibb.co/q7KgLxC/images-3.jpg',
        photo: 'https://i.ibb.co/X34C98F/Screen-Shot-2019-04-05-at-11-42-19-PM.png'
    },
    {
        id: '24',
        category: 'Spices',
        name:' Red Chili',
        color: 'red',
        originOfBasil: 'Egypt',
        Type: 'Size: Depend on Customers Needs',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : 'Grade:TOP GRADE',
        purity : 'Purity: High',
        Moisture: 'Moisture 5% max.',
        Usage: 'Foreign Materials:No Foreign Materials or Ash 0',
        feet: '6 ton / 20FCL - 12 ton / 40FCL.',
        description:' Used: Culinary, Medicinal ,flavor , industry & Tea',
        image: 'https://i.ibb.co/yN5FStt/cayenne-pepper-png-images-free-png-library-chili-peppers-png-3552-2796.png',
        photo: 'https://i.ibb.co/yN5FStt/cayenne-pepper-png-images-free-png-library-chili-peppers-png-3552-2796.png'
    }, 
    {
        id: '25',
        category: 'Spices',
        name:'Rosemary',
        color: 'green',
        originOfBasil: 'Egypt',
        Type: ' conventional rosemary and organic rosemary.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Grade: TOP GRADE ',
        Moisture: 'Moisture 5% max.',
        Usage: 'Spices',
        feet: '20 ft container load of rosemary :6 ton - 40 ft container load of rosemary :12 ton .',
        description:'Description :Drying Process :"SD" Sun dried - Size: Depend on Customers Needs - Aroma: Pungent Sweet -  Flavor:Characteristic flavor',
        image: 'https://i.ibb.co/tZ3Nmj6/rosemary-rosemary-rosemary-flowering-rosemary-tattoo-11563248681i5hkdlyjfn.png',
        photo: 'https://i.ibb.co/THQP77G/114-1143163-transparent-rosemary-png.png'
    },
    {
        id: '26',
        category: 'Spices',
        name:'Thyme',
        color: 'green',
        originOfBasil: 'Egypt',
        Type: ' conventional anise and organic basil.',
        harvestSeason: 'Available throughout the year ',
        SmellAndTaste : ' aromatic, typical.',
        purity : 'Purity 99% and Admixture 1% ',
        Moisture: 'Moisture 5%.',
        Usage: 'Part use:  thyme',
        feet: '20 ft container load of Thyme :7 ton - 40 ft container load of Thyme :14 ton .',
        description:' uses Thyme is by mouth for bronchitis, whooping cough, sore throat, colic, arthritis, upset stomach, stomach pain gastritis, diarrhea, bedwetting, a movement disorder in children dyspraxia, intestinal gas flatulence, parasitic worm infections, and skin disorders .',
        image: 'https://i.ibb.co/ZSJqY8X/flower-garden-thyme-herb-food-garden-thyme-spice-essential-oil-coriander-png-clipart.jpg',
        photo: 'https://i.ibb.co/ZSJqY8X/flower-garden-thyme-herb-food-garden-thyme-spice-essential-oil-coriander-png-clipart.jpg'
    },
]
export default SpicesAPI;